### PR TITLE
Rewrite CLI using oclif

### LINKED ISSUE #28: Cannot login
Hi.
There is a "Nuxt.js Sample multi-page website with navigation" sample on your website that I'm trying to follow. Unfortunately, running
`prismic theme https://github.com/prismicio/nuxtjs-website.git --conf prismic.config.js`,
I couldn't pass the account login step. No error displayed, just always back to asking my username and password again.

### PR DESCRIPTION
**Pull request by iwatakeshi**
Hi,

This PR is a complete rewrite of the CLI using [oclif](https://oclif.io/).

It should fix #28 and although not implemented, it should also address #11 for extensibility.

With this pull request, you should be able to add additional commands with ease. In addition, most of the code is annotated and should be easier to understand what type of data is expected since it's written in TypeScript.

I will admit, [trying to understand](https://github.com/prismicio/prismic-cli/issues/11#issuecomment-283232768) the current codebase was a daunting task. Therefore, some features that are available now may not be available in the new version. 

Here's a brief overview of what works:

* __Authentication__ - `signin`, `signout`
    * Both commands have been tested manually using cookies. Magic links are supported but I haven't tried it yet.
    * `signup` seems to work. I've only tried it against an existing account.
    * The `--status` flag is available if you want to check whether you are signed in or not.

* __Project creation__ - `new`
    * `new` can create a repository and scaffold a project based on a theme or template (if no theme is specified). It can also generate a quickstart project using the`--quickstart` flag.
  * `init` is also available. However, I'm not entirely sure what exactly is the role of `init`, other than it doesn't create a remote repository. This is something to discuss about.

For the full list of commands, oclif automatically generates them and can been seen in the [readme](https://github.com/iwatakeshi/prismic-cli/tree/chore/rewrite-using-oclif#prismic-cli)

The commands that are not listed are:

* `heroku` - Probably not hard to implement, but I question whether it needs to be a command. This could simply be a flag as well. e.g. `--heroku | -h`
* `base` - Should work but I haven't tested it. It's hidden by default.

Other things to consider:

* The code is written for `node >= 10`
* Only critical tests have been made for `communication.ts` and `config.ts`.
* Try it first by using `yarn link` or `npm link`
* Create a branch for this new version to merge into
* One of the tests in `communication.ts` requires a environment variable to work.

I know this is a lot and if you guys were in the middle of doing some work, then I apologize for the inconvenience. However, if you have any questions, feel free to ask.

Thank you

### CODE REVIEW

**Comment by evolve2k** [comment]
bump. Looks like a great initiative. Can we get a comment on this from the core team. 
Im sure @iwatakeshi would be willing to resolve conflicts and give it further polish if they know this is moving ahead.

Can you allocate some team time to review this and come back to us.
It's good practice to encourage proactive open source contributions like this.

I'd encourage you to keep this moving.

**Comment by arnaudlewis** [comment]
Hello @iwatakeshi, Thanks for this amazing contribution, I'm gonna take a closer look but I wanted to make the migration to OCLIF at some point so it looks like a great opportunity.
Obviously we did a lot of updates on the CLI and we integrated slicemachine but that could be a good base.
Basically what I want for our CLI is two have a very simple way to integrate community plugins.
I'm not an OCLIF expert and I don't know if we would just reference different plugins to build the CLI, if there is a way to install interactively plugins on-demand but anyway you see the idea.
It would be super helpful for slicemachine, each time we want to support a new feature or even support a new technology, we could dedicate a plugin for it and ask the community either to build some or to contribute.
What do you think about that?
Anyway I'm looking at it so I'll give you some feedback real soon

**Comment by iwatakeshi** [comment]
@evolve2k Thanks for bumping! 👊 .

@arnaudlewis 

Hi, thank you for the comment.

>what I want for our CLI is two have a very simple way to integrate community plugins.

I believe `OCLIF` can handle that use case quite easily. There's a [plugin](https://github.com/oclif/plugin-plugins) for `OCLIF` to allow end-users install plugins for the CLI. However, I'm not an expert either so it will be a matter of trial and error to get it right it 😅 .

> It would be super helpful for slicemachine, each time we want to support a new feature or even support a new technology, we could dedicate a plugin for it and ask the community either to build some or to contribute.

I think I did see a reference to it (but, I think I removed it in the process 😅 ). It will take me a few days to look into my codebase and refresh my memory but as @evolve2k brought it up, I'll be more than happy to go through and update the repo. Anyways, I think that the idea of allowing users to extend the CLi is a great idea.

**Comment by MarcMcIntosh** [comment]
Hi, I guess we took this idea and ran with it, the cli has been rewritten with oclif + typscript.

Thanks for making the effort :)

**Pull request closed without merging**
